name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Pure Minimal Dependencies
      run: |
        sudo apt-get update || true
        # Оставили только самый неубиваемый минимум пакетов
        sudo apt-get install -y git zip unzip encode libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev python3-pip
        pip3 install --user --upgrade buildozer cython virtualenv

    - name: Build Android APK with Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        # Чистим старые кэши перед сборкой, если они были
        buildozer ac_clean || true
        yes | buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RainyOS-APK
        path: .buildozer/android/app/build/outputs/apk/debug/*.apk
