name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: ArtemGovorov/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RainyOS-APK
        path: .buildozer/android/app/build/outputs/apk/debug/*.apk
